[maneuverconfig]

maneuvers = [
  "yank n bank",
  "jet fuel therapy",
  "100LL cowboy",
  "lorem ipsum 1",
  "barrel roll with it",
  "skyline symphony",
  "rudder of destiny",
  "rollin' in the clouds",
  "aero-nonsense",
  "tailspin tango",
  "afterburner attitude",
  "tailhook twist",
  "altitude adjustment",
  "throttle therapy",
  "prop wash parley",
  "high speed high jinks",
  "control surface shuffle",
  "wingman waltz",
  "jetstream jive",
  "climb and glide",
  "nose dive narrative",
  "altimeter anecdotes",
  "fighter jet folly",
  "spin cycle surprise",
  "vortex vignettes",
  "aerofoils of fun",
  "turbo twist",
  "barrel barrel barrel",
  "cleared for takeoff",
]